import os


def calculate_wage(data):
    import joblib
    path = os.path.join("model", "v1")
    model = joblib.load(os.path.join(path, "income_model.pkl"))
    imputer = joblib.load(os.path.join(path, "imputer.pkl"))
    print(data)
    input_data = {
        "Company HQ": data['company_hq'],
        "Company Size": data['company_size'],
        "Experience": data['experience'],
        "Gender": data['gender'],
        "Remote / On-Site / Both": data['way_of_working'],
        "Team Leader": data['team_leader'],
        "Education": data['education'],
        "AI / ML": data["AI / ML"],
        "Architect": data["Architect"],
        "Automation": data["Automation"],
        "BI": data["BI"],
        "Backend": data["Backend"],
        "Big Data": data["Big Data"],
        "Bioinformatics": data["Bioinformatics"],
        "Blockchain": data["Blockchain"],
        "CRM": data["CRM"],
        "Cybersecurity": data["Cybersecurity"],
        "Data Science": data["Data Science"],
        "Data engineer": data["Data engineer"],
        "Database": data["Database"],
        "Desktop apps": data["Desktop apps"],
        "DevOps": data["DevOps"],
        "ERP": data["ERP"],
        "Embedded": data["Embedded"],
        "Engineering Manager": data["Engineering Manager"],
        "FPGA/ASIC": data["FPGA/ASIC"],
        "Fintech": data["Fintech"],
        "Framework Building": data["Framework Building"],
        "Frontend": data["Frontend"],
        "Full Stack": data["Full Stack"],
        "Gaming": data["Gaming"],
        "Hardware": data["Hardware"],
        "Helpdesk": data["Helpdesk"],
        "IT Engineer": data["IT Engineer"],
        "IT Manager": data["IT Manager"],
        "Integration Engineering": data["Integration Engineering"],
        "Mobile apps": data["Mobile apps"],
        "Networking": data["Networking"],
        "QA Automation Engineer": data["QA Automation Engineer"],
        "Research Engineer": data["Research Engineer"],
        "Robotics": data["Robotics"],
        "SAP Developer": data["SAP Developer"],
        "SDET": data["SDET"],
        "SaaS Engineer": data["SaaS Engineer"],
        "Simulation": data["Simulation"],
        "Site reliability engineering": data["Site reliability engineering"],
        "Software Engineer": data["Software Engineer"],
        "Solutions Engineer": data["Solutions Engineer"],
        "System Engineer": data["System Engineer"],
        "Systems": data["Systems"],
        "Test engineer": data["Test engineer"],
        "ABAP": data["ABAP"],
        "AL": data["AL"],
        "Angular": data["Angular"],
        "Apex": data["Apex"],
        "Assembly": data["Assembly"],
        "Bash": data["Bash"],
        "Bootstrap": data["Bootstrap"],
        "C": data["C"],
        "C#": data["C#"],
        "C++": data["C++"],
        "C/AL": data["C/AL"],
        "CSS": data["CSS"],
        "Cobol": data["Cobol"],
        "Dart": data["Dart"],
        "Delphi": data["Delphi"],
        "FORTRAN": data["FORTRAN"],
        "Flutter": data["Flutter"],
        "Go": data["Go"],
        "Groovy": data["Groovy"],
        "HCL": data["HCL"],
        "HTML": data["HTML"],
        "Java": data["Java"],
        "JavaScript": data["JavaScript"],
        "Kotlin": data["Kotlin"],
        "Kubernetes": data["Kubernetes"],
        "LaTeX": data["LaTeX"],
        "MySQL": data["MySQL"],
        "Node": data["Node"],
        "NodeJS": data["NodeJS"],
        "Objective-C": data["Objective-C"],
        "PHP": data["PHP"],
        "PL/SQL": data["PL/SQL"],
        "Perl": data["Perl"],
        "PostgreSQL": data["PostgreSQL"],
        "PowerBuilder": data["PowerBuilder"],
        "Python": data["Python"],
        "R": data["R"],
        "React": data["React"],
        "React Native": data["React Native"],
        "Ruby": data["Ruby"],
        "Rust": data["Rust"],
        "SAS": data["SAS"],
        "SQL": data["SQL"],
        "Scala": data["Scala"],
        "Solidity": data["Solidity"],
        "Swift": data["Swift"],
        "SystemVerilog": data["SystemVerilog"],
        "T-SQL": data["T-SQL"],
        "TCL": data["TCL"],
        "Terraform": data["Terraform"],
        "TypeScript": data["TypeScript"],
        "VB.NET": data["VB.NET"],
        "VHDL": data["VHDL"],
        "Visual Basic": data["Visual Basic"],
        "Vue": data["Vue"],
        "Wordpress": data["Wordpress"],
        "X++": data["X++"],
        "YAML": data["YAML"],
    }
    keys_list = list(input_data.values())
    new_data = [keys_list]

    new_data = imputer.transform(new_data)

    prediction = model.predict(new_data)

    print("Predicted Yearly Income:", prediction[0])
    print("Monthly Income:", prediction[0] / 14)